name: quick_mart
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  flutter_svg: ^2.0.10+1
  email_validator: ^3.0.0

  # provider
  provider: ^6.1.2

  # icons
  cupertino_icons: ^1.0.2

  # show toast
  fluttertoast: ^8.2.5

  # read_more_text
  readmore: ^3.0.0

  # router
  go_router: ^14.2.3

  # shared_preferences
  shared_preferences: ^2.2.3

  # Hive
  hive: ^2.2.3
  build_runner: ^2.4.9
  hive_flutter: ^1.1.0
  hive_generator: ^1.0.0

  # Firebase
  firebase_remote_config: ^4.3.17
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_analytics: any
  firebase_messaging: 14.9.4
  flutter_local_notifications: ^16.3.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.7

  # logger
  logger: ^1.1.0

  #permission
  permission_handler: ^11.3.1


  # images animation
  lottie: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/icon_app.png"
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
   - assets/icons/
   - assets/icons/icon_navbar/
   - assets/images/
   - assets/images_animation/

flutter_intl:
  enabled: true